### PR TITLE
Add a section (11) on building custom R

### PR DESCRIPTION
**Pull request by grantbrown**
Students in 7600 requested info on getting the latest R. Mind taking a look?

### CODE REVIEW

**Comment by pbreheny** [comment]
Looks good!

**Comment by pbreheny** [comment]
Just curious: so you don't use `configure --prefix` or `make install`?

FYI: I added your name to the footer.

**Comment by grantbrown** [comment]
Good point, I'm personally OK with the default binary location, but that
might be clearer for other users. I can modify it.

-Grant

**Comment by pbreheny** [comment]
Yeah, I'm not sure -- I think it would make sense to go with whatever is easiest for students to understand, but I'm not sure which approach that is.

Separate question: Is there a typo on the last line?

```
alias -p R="~/build
```

doesn't look right.

**Comment by grantbrown** [comment]
Yep, the end of the line was missing. Good catch.

**Pull request merged**
